### ISSUE TITLE
General/ Improve README

### ISSUE THREAD

**Issue by h1alexbel** [l3r8yJ/elegram-api#24]
We need to improve README file about the project.
Need to include this information:
```Which problem this project solves```, 
```Why this problem was not solved by other people/repos```,
```How it works```.
I'm sure that these details will improve this repository, and the whole project itself.
What do you think? @l3r8yJ

**Comment by l3r8yJ** [comment]
@h1alexbel good idea

**Comment by l3r8yJ** [comment]
@h1alexbel I' ve made some improvements, please take a look at `README`, what do you think?

**Comment by h1alexbel** [comment]
> @h1alexbel I' ve made some improvements, please take a look at `README`, what do you think?

So far, so good.
