### ISSUE TITLE
General/ Java 17 Support

### ISSUE THREAD

**Issue by h1alexbel** [l3r8yJ/elegram-api#26]
So, as I can see [here](https://github.com/l3r8yJ/elegram-api/blob/master/pom.xml) we support java 8, but Java 17 is here. Maybe we can support 17 SE version by default?

**Comment by l3r8yJ** [comment]
@h1alexbel I also thought about it, but I have problems with `qulice`, if you can integrate version 17, I would be great

**Comment by l3r8yJ** [comment]
@h1alexbel will you try to close this ticket?

**Comment by h1alexbel** [comment]
> @h1alexbel will you try to close this ticket?

Yes, but a bit later.

**Comment by h1alexbel** [comment]
Hey @l3r8yJ , I've updated the project with ```java 17```, so ```qulice``` doesn't complains.

There is the result of ```mvn clean install```:
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/83453843/205641621-d77d62ae-b468-4b13-b548-da0385affd08.png">

**Comment by h1alexbel** [comment]
Also,  ```mvn clean install -Pqulice``` works fine

**Comment by l3r8yJ** [comment]
@h1alexbel `qulice` check included into `mvn clean install`, it seemed to me that it would be more convenient

**Comment by l3r8yJ** [comment]
closed as completed
