### ISSUE TITLE
Redesign/GetUpdates

### ISSUE THREAD

**Issue by l3r8yJ** [l3r8yJ/elegram-api#38]
Change the design of this class and make it like `RqFileTelegram`.

**Comment by Japsty** [comment]
@l3r8yJ  
I'll try

**Comment by Japsty** [comment]
@l3r8yJ  I don't have much time to do it now,  can you cancel assignment?

**Comment by l3r8yJ** [comment]
@Japsty you can do it later

**Comment by l3r8yJ** [comment]
@Japsty we need to close it now, so i remove assignment from you, you can take another [issue](https://github.com/l3r8yJ/elegram-api/issues).
