### ISSUE TITLE
RqSendMessageTelegram

### ISSUE THREAD

**Issue by l3r8yJ** [l3r8yJ/elegram-api#41]

**Comment by 0pdd** [comment]
@l3r8yJ 3 puzzles [#43](https://github.com/l3r8yJ/elegram-api/issues/43), [#44](https://github.com/l3r8yJ/elegram-api/issues/44), [#45](https://github.com/l3r8yJ/elegram-api/issues/45) are still not solved.

**Comment by 0pdd** [comment]
@l3r8yJ 2 puzzles [#44](https://github.com/l3r8yJ/elegram-api/issues/44), [#45](https://github.com/l3r8yJ/elegram-api/issues/45) are still not solved; solved: [#43](https://github.com/l3r8yJ/elegram-api/issues/43).

**Comment by 0pdd** [comment]
@l3r8yJ the puzzle [#45](https://github.com/l3r8yJ/elegram-api/issues/45) is still not solved; solved: [#43](https://github.com/l3r8yJ/elegram-api/issues/43), [#44](https://github.com/l3r8yJ/elegram-api/issues/44).

**Comment by 0pdd** [comment]
@l3r8yJ all 3 puzzles are solved here: [#43](https://github.com/l3r8yJ/elegram-api/issues/43), [#44](https://github.com/l3r8yJ/elegram-api/issues/44), [#45](https://github.com/l3r8yJ/elegram-api/issues/45).
