### ISSUE TITLE
Core/ Make an experimental implementation of DefaultBot

### ISSUE THREAD

**Issue by l3r8yJ** [l3r8yJ/elegram-api#53]

**Comment by 0pdd** [comment]
@l3r8yJ 2 puzzles [#55](https://github.com/l3r8yJ/elegram-api/issues/55), [#56](https://github.com/l3r8yJ/elegram-api/issues/56) are still not solved.

**Comment by 0pdd** [comment]
@l3r8yJ all 2 puzzles are solved here: [#55](https://github.com/l3r8yJ/elegram-api/issues/55), [#56](https://github.com/l3r8yJ/elegram-api/issues/56).
