### ISSUE TITLE
DefaultBot.java:25-27: Design/ Implement run(). Need to...

### ISSUE THREAD

**Issue by 0pdd** [l3r8yJ/elegram-api#60]
The puzzle `70-3d00acb6` from #70 has to be resolved: 

https://github.com/l3r8yJ/elegram-api/blob/4cf22e1afe1fd9da5c81717c006923eab25d3d26/src/main/java/com/l3r8yj/elegramapi/bot/DefaultBot.java#L25-L27

The puzzle was created by @h1alexbel on 05-Dec-22. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by h1alexbel** [comment]
Maybe we need to decompose it.
@l3r8yJ

**Comment by l3r8yJ** [comment]
@h1alexbel sure go ahead, it's this issue more like reminder

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#68](https://github.com/l3r8yJ/elegram-api/issues/68), [#69](https://github.com/l3r8yJ/elegram-api/issues/69), [#70](https://github.com/l3r8yJ/elegram-api/issues/70), [#71](https://github.com/l3r8yJ/elegram-api/issues/71), [#72](https://github.com/l3r8yJ/elegram-api/issues/72) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown]() are still not solved.

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#unknown](), [#unknown](), [#unknown](), [#unknown]() are still not solved.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#unknown](), [#unknown](), [#unknown]() are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
