### ISSUE TITLE
DefaultUpdate.java:25-28: Core/ Implement Update....

### ISSUE THREAD

**Issue by 0pdd** [l3r8yJ/elegram-api#68]
The puzzle `60-b481fc5e` from #60 has to be resolved: 

https://github.com/l3r8yJ/elegram-api/blob/d91f19eb2b9a899c96be33c26dea79bfc46543aa/src/main/java/com/l3r8yj/elegramapi/update/DefaultUpdate.java#L25-L28

The puzzle was created by @l3r8yJ on 14-Jan-23. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by l3r8yJ** [comment]
@0pdd close as solved
