### ISSUE TITLE
DefaultBot.java:29-33: Design/ Handling. Base handling...

### ISSUE THREAD

**Issue by 0pdd** [l3r8yJ/elegram-api#70]
The puzzle `60-7d61ce0e` from #60 has to be resolved: 

https://github.com/l3r8yJ/elegram-api/blob/d91f19eb2b9a899c96be33c26dea79bfc46543aa/src/main/java/com/l3r8yj/elegramapi/bot/DefaultBot.java#L29-L33

The puzzle was created by @l3r8yJ on 14-Jan-23. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@0pdd 6 puzzles [#60](https://github.com/l3r8yJ/elegram-api/issues/60), [#68](https://github.com/l3r8yJ/elegram-api/issues/68), [#69](https://github.com/l3r8yJ/elegram-api/issues/69), [#70](https://github.com/l3r8yJ/elegram-api/issues/70), [#71](https://github.com/l3r8yJ/elegram-api/issues/71), [#72](https://github.com/l3r8yJ/elegram-api/issues/72) are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#unknown]() is solved here.

**Comment by l3r8yJ** [comment]
closed as solved
