### ISSUE TITLE
onUpdate method

### ISSUE THREAD

**Issue by l3r8yJ** [l3r8yJ/elegram-api#73]
transfer `onUpdate` method from `Command` to `DefaultBot` and make `DefaultBot` abstract class

**Comment by 0pdd** [comment]
@l3r8yJ the puzzle [#75](https://github.com/l3r8yJ/elegram-api/issues/75) is still not solved.

**Comment by 0pdd** [comment]
@l3r8yJ the only puzzle [#75](https://github.com/l3r8yJ/elegram-api/issues/75) is solved here.
