### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by l3r8yJ** [l3r8yJ/elegram-api#94]
Create an integration tests with `invoker` maven plugin

**Comment by 0pdd** [comment]
@l3r8yJ the puzzle [#106](https://github.com/l3r8yJ/elegram-api/issues/106) is still not solved.

**Comment by 0pdd** [comment]
@l3r8yJ the puzzle [#115](https://github.com/l3r8yJ/elegram-api/issues/115) is still not solved; solved: [#106](https://github.com/l3r8yJ/elegram-api/issues/106).
